server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    druid:
      url: jdbc:mysql://10.0.26.128:3306/nacos_config?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: nacos_config
      password: '#Zxb12345'
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos 服务注册地址
    alibaba:
      seata:
        tx-service-group: my_tx_group

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.0.26.128:3306/nacos_config?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: nacos_config
#    password: '#Zxb12345'
feign:
  hystrix:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.alibaba.domain

