server:
  port: 7002

eureka:
  instance:
    #hostname: localhost #euraka 服务端的实例名称 单机版
    hostname: eureka7002.com #euraka 服务端的实例名称 集群
  client:
    register-with-eureka: false # false 表示不注册自己 true 表示注册自己
    fetch-registry: false  #false 表示自己就是注册端
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版
      defaultZone: http://eureka7001.com:7001/eureka/  #集群
