server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      url: jdbc:mysql://10.0.26.128:3306/icenter?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: icenter
      password: icenter#DEV0903
      driver-class-name: com.mysql.cj.jdbc.Driver
 # 全链路 sleuth 配置信息
# https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec
# cd D:\jimmy_down
# java -jar  zipkin-server-2.12.9-exec.jar#

# http://localhost:9411/zipkin/
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于0到1 之间，1则表示全部采集


#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#      #org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://10.0.26.128:3306/icenter?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: icenter
#    password: icenter#TEST0309

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # 单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true #表示显示访问ip地址
    # 心跳发发送频率 默认30s
    lease-renewal-interval-in-seconds: 1
    # 设置过期剔除时间（单位秒） 默认 90s
    lease-expiration-duration-in-seconds: 5
