server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版


##设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
#ribbon:
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ConnectTimeout: 5000

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 6000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 10000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug