server:
  port: 80

spring:
  application:
    name: cloud-order-service
  # 全链路 sleuth 配置信息
  # https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec
  # cd D:\jimmy_down
  # java -jar  zipkin-server-2.12.9-exec.jar#

  # http://localhost:9411/zipkin/
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于0到1 之间，1则表示全部采集

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
