server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh1 # 路由id，没有固定的规则，但要求唯一，建议配合服务器名称
#          uri: http://localhost:8001 #匹配后的服务地址
          uri: lb://cloud-payment-service #匹配后的服务地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配后进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2021-06-17T11:36:15.153+08:00[Asia/Shanghai]
            #- Before=2021-06-17T11:36:15.153+08:00[Asia/Shanghai]
            #- Between=2021-06-17T11:36:15.153+08:00[Asia/Shanghai],2021-06-17T14:36:15.153+08:00[Asia/Shanghai]
            #- Cookie=userName,test   #一个是Cookie名称，一个是正则表达式
            # curl -b "userName=test" http://localhost:9527/payment/lb?uname=55
            # curl http://localhost:9527/payment/lb?uname=55 --cookie "userName=test"
            #- Header=X-Request-Id,\d+ # 与Cookie 相似
            #curl -H "X-Request-Id:123" http://localhost:9527/payment/lb?uname=55
            #- Host=**.baidu.com
            #curl -H "Host: www.baidu.com" http://localhost:9527/payment/lb?uname=55
            #curl -H "Host: news.baidu.com" http://localhost:9527/payment/lb?uname=55
            #- Method=GET
            #- Query=userName,\0+ # 与Cookie 相似 curl  http://localhost:9527/payment/lb?userName=55



# 2*3*3*5
# CloudFoundryRouteService|ReadBodyPredicateFactory
# Before|After|Between   <---ZonedDateTime.now()
# Host|RemoteAddr|Weight
# Path|Query|Method|Header|Cookie


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka