server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080  # 配置sentinel dashboard地址
        port: 8719

# 消费者要去访问的微服务名称
service-uri:
  nacos-user-service: http://nacos-payment-provider

# 激活sentinel 对 openfeign 的支持
feign:
  sentinel:
    enabled: true
